common/models/MhConcrete.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Html;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mh_concrete".
 *
 * @property int $con_id รหัสรายละเอียดคอนกรีต
 * @property int $user_id ชื่อผู้ใช้
 * @property string $con_desciption_product รายละเอียดคอนกรีต
 * @property int $con_strength กำลังแรงอัด
 * @property int $con_volume ปริมาณ
 * @property string $con_unit หน่วย
 * @property int $con_cube Cube
 * @property int $con_cylender Cylender
 * @property string $con_gps_transpot พิกัด GPS
 * @property int $con_province_id จังหวัด
 * @property int $con_amphoe_id อำเภอ
 * @property int $con_district_id ตำบล
 * @property string $con_pic_map รูปแผนที่
 * @property string $con_datetime วันที่
 * @property string $con_duration ช่วงเวลา เช้า บ่าย
 * @property string $con_name_contact con_name_contact
 * @property int $con_tel_contact con_tel_contact
 * @property string $con_other con_other
 * @property int $updated_id รหัสเวลาแก้ไข
 * @property string $created_time เวลาสร้าง
 * @property string $updated_time เวลาแก้ไข
 *
 * @property MhProvince $conProvince
 * @property MhAmphoe $conAmphoe
 * @property MhDistrict $conDistrict
 * @property MhUser $user
 */
class MhConcrete extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mh_concrete';
    }

    public $upload_foler = 'uploads';
    public $picture = 'nonee.png';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'con_strength', 'con_volume', 'con_cube', 'con_cylender', 'con_province_id', 'con_amphoe_id', 'con_district_id', 'con_tel_contact', 'updated_id'], 'integer'],
            [['con_strength', 'con_volume', 'con_datetime', 'con_duration', 'con_name_contact', 'con_tel_contact'], 'required'],
            [['con_unit', 'con_duration'], 'string'],
            [['con_datetime', 'created_time', 'updated_time'], 'safe'],
            [['con_desciption_product', 'con_gps_transpot', 'con_other'], 'string', 'max' => 255],
            [['con_name_contact'], 'string', 'max' => 150],
            [['con_province_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhProvince::className(), 'targetAttribute' => ['con_province_id' => 'province_id']],
            [['con_amphoe_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhAmphoe::className(), 'targetAttribute' => ['con_amphoe_id' => 'amphoe_id']],
            [['con_district_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhDistrict::className(), 'targetAttribute' => ['con_district_id' => 'district_id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhUser::className(), 'targetAttribute' => ['user_id' => 'user_id']],
            [
                ['con_pic_map'], 'file',
                'skipOnEmpty' => true,
                'maxFiles' => 5,
                'extensions' => 'png,jpg,jpeg,gif',
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'con_id' => 'รหัสรายละเอียดคอนกรีต',
            'user_id' => 'ชื่อผู้ใช้งาน',
            'con_desciption_product' => 'รายละเอียดคอนกรีต',
            'con_strength' => 'กำลังแรงอัด',
            'con_volume' => 'ปริมาณ',
            'con_unit' => 'หน่วย',
            'con_cube' => 'Cube',
            'con_cylender' => 'Cylender',
            'con_gps_transpot' => 'พิกัด GPS',
            'con_province_id' => 'จังหวัด',
            'con_amphoe_id' => 'อำเภอ',
            'con_district_id' => 'ตำบล',
            'con_pic_map' => Yii::t('app', 'รูปแผนที่'),
            'con_datetime' => 'วันที่ต้องการส่ง',
            'con_duration' => 'ช่วงเวลาที่ต้องการส่ง',
            'con_name_contact' => 'ชื่อติดต่อ',
            'con_tel_contact' => 'เบอร์โทรศัพท์',
            'con_other' => 'อื่นๆ',
            'updated_id' => 'รหัสเวลาแก้ไข',
            'created_time' => 'เวลาสร้าง',
            'updated_time' => 'เวลาแก้ไข',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConProvince()
    {
        return $this->hasOne(MhProvince::className(), ['province_id' => 'con_province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConAmphoe()
    {
        return $this->hasOne(MhAmphoe::className(), ['amphoe_id' => 'con_amphoe_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConDistrict()
    {
        return $this->hasOne(MhDistrict::className(), ['district_id' => 'con_district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(MhUser::className(), ['user_id' => 'user_id']);
    }

    public function pickup()
    {
        $result = '';
        if (($this->con_province_id != null) && ($this->con_province_id != '')) {
            $resultcoll = MhProvince::find()
                ->where(['province_id' => $this->con_province_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->province_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    public function deliver()
    {
        $result = '';
        if (($this->con_amphoe_id != null) && ($this->con_amphoe_id != '')) {
            $resultcoll = MhAmphoe::find()
                ->where(['amphoe_id' => $this->con_amphoe_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->amphoe_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    public function upload($model, $attribute)
    {
        $picture  = UploadedFile::getInstance($model, $attribute);
        $path = $this->getUploadPath();
        if ($this->validate() && $picture !== null) {

            $fileName = md5($picture->baseName . time()) . '.' . $picture->extension;
            if ($picture->saveAs($path . $fileName)) {
                return $fileName;
            }
        }
        return $model->isNewRecord ? false : $model->getOldAttribute($attribute);
    }

    public function getUploadPath()
    {
        return Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/';
    }

    public function getUploadUrl()
    {
        return Yii::getAlias('../common/web') . '/' . $this->upload_foler . '/';
    }

    public function getPhotoViewer()
    {
        return empty($this->picture) ? Yii::getAlias('../../common/web') . '/img/none.png' : $this->getUploadUrl() . $this->picture;
    }

    public function getUploadUrlback()
    {
        return Yii::getAlias('../../common/web') . '/' . $this->upload_foler . '/';
    }

    public function getPhotoViewerback()
    {
        return empty($this->picture) ? Yii::getAlias('../../common/web') . '/img/none.png' : $this->getUploadUrlback() . $this->picture;
    }




    public function uploadMultiple($model, $attribute)
    {
        $photos  = UploadedFile::getInstances($model, $attribute);
        $path = $this->getUploadPath();
        if ($this->validate() && $photos !== null) {
            $filenames = [];
            foreach ($photos as $file) {
                $filename = md5($file->baseName . time()) . '.' . $file->extension;
                if ($file->saveAs($path . $filename)) {
                    $filenames[] = $filename;
                }
            }

            if ($model->isNewRecord) {
                return implode(',', $filenames);
            } else {
                if (sizeof($filenames) == 0) {
                    return implode(',', (ArrayHelper::merge($filenames, $model->getOwnPhotosToArray())));
                } else {
                    return implode(',', $filenames);
                }
            }
        }

        return $model->isNewRecord ? false : $model->getOldAttribute($attribute);
    }

    public function getPhotosViewer()
    {
        $photos = $this->con_pic_map ? @explode(',', $this->con_pic_map) : [];
        $img = '';
        foreach ($photos as $photo) {
            $img .= ' ' . Html::img($this->getUploadUrl() . $photo, ['class' => 'img-thumbnail', 'style' => 'max-width:200px;']);
        }
        return $img;
    }

    public function getPhotosViewerback()
    {
        $photos = $this->con_pic_map ? @explode(',', $this->con_pic_map) : [];
        $img = '';
/*
        var_dump($photos);
        die();
*/
        foreach ($photos as $photo) {
            $img .= ' ' . Html::img($this->getUploadUrlback() . $photo, ['class' => 'img-thumbnail', 'style' => 'max-width:200px;']);
        }
        return $img;
    }

    public function getFirstPhotos()
    {
        $con_pic_map = $this->con_pic_map ? @explode(',', $this->con_pic_map) : [];
        $img = Html::img(Yii::getAlias('../../common/web') . '/img/none.png', ['class' => 'img-responsive', 'style' => 'max-width:200px;']);
        if (isset($con_pic_map[0])) {
            $img = Html::img($this->getUploadUrl() . $con_pic_map[0], ['class' => 'img-responsive', 'style' => 'max-width:200px;']);
        }
        return $img;
    }

    public function getFirstPhotoURL()
    {
        $con_pic_map = $this->con_pic_map ? @explode(',', $this->con_pic_map) : [];
        $img = Yii::getAlias('../../common/web') . '/img/none.png';
        if (isset($con_pic_map[0])) {
            $img = $this->getUploadUrl() . $con_pic_map[0];
        }
        return $img;
    }


    public function getFirstPhotosback()
    {
        $con_pic_map = $this->con_pic_map ? @explode(',', $this->con_pic_map) : [];
        $img = Html::img(Yii::getAlias('../../common/web') . '/img/none.png', ['class' => 'img-responsive', 'style' => 'max-width:200px;']);
        if (isset($con_pic_map[0])) {

frontend/controllers/MhConcreteController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\MhConcrete;
use backend\models\MhConcreteSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use common\models\MhAmphoe;
use common\models\MhDistrict;

/**
 * MhConcreteController implements the CRUD actions for MhConcrete model.
 */
class MhConcreteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhConcrete models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $searchModel = new MhConcreteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view_all_conlist', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    

    public function actionMycon()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;

        $searchModel = new MhConcreteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider
        ->query
        ->where(['in', 'user_id', $user_id]);

        return $this->render('my_con', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            
        ]);
}

    /**
     * Displays a single MhConcrete model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $owner = false;

        $user_id = Yii::$app->user->id;
        if ($model->user_id == $user_id) {
            $owner = true;
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
            'owner' => $owner,
        ]);
    }

    /**
     * Creates a new MhConcrete model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        /*if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }*/
        $model = new MhConcrete();

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->con_pic_map = $model->uploadMultiple($model, 'con_pic_map');               
                
            }

            if(Yii::$app->request->isPost) {
                
                    $con_desciption_product = Yii::$app->request->post('MhConcrete[con_desciption_product]');
                    Yii::$app->mailer->compose()
                    ->setTo('fusefeaturing@gmail.com')
                    ->setFrom('fusefeaturing@gmail.com')
                    ->setSubject('ทดสอบ')
                    ->setHtmlBody('<b>'.$con_desciption_product.'</b>')
                    ->setBcc('fusefeaturing@gmail.com')
                    
                    ->send();
        
                  
                  
            }

            if ($model->save()) {
                //return $this->redirect(['view', 'id' => $model->job_id]);
                return $this->redirect(['view', 'id' => $model->con_id]);
            }

        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MhConcrete model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        $amphoe = ArrayHelper::map($this->getAmphoe($model->con_amphoe_id), 'id', 'name');
        $district = ArrayHelper::map($this->getDistrict($model->con_district_id), 'id', 'name');

        if ($model->load(Yii::$app->request->post())) {

            
            if ($model->validate()) {
                $model->con_pic_map = $model->uploadMultiple($model, 'con_pic_map');
            }

            if ($model->save()) {
                //return $this->redirect(['view', 'id' => $model->job_id]);
                return $this->redirect(['view', 'id' => $model->con_id]);
            }

        }

        return $this->render('update', [
            'model' => $model,
            'amphoe' => $amphoe,
            'district' => $district,
        ]);
    }

    /**
     * Deletes an existing MhConcrete model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhConcrete model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhConcrete the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhConcrete::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetAmphoe()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $province_id = $parents[0];
                $out = $this->getAmphoe($province_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionGetDistrict()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $province_id = empty($ids[0]) ? null : $ids[0];
            $amphoe_id = empty($ids[1]) ? null : $ids[1];
            if ($province_id != null) {
                $data = $this->getDistrict($amphoe_id);
                echo Json::encode(['output' => $data, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getAmphoe($id)
    {
        $datas = MhAmphoe::find()->where(['province_id' => $id])->all();
        return $this->MapData($datas, 'amphoe_id', 'amphoe_name_th');
    }

    protected function getDistrict($id)
    {
        $datas = MhDistrict::find()->where(['amphoe_id' => $id])->all();
        return $this->MapData($datas, 'district_id', 'district_name_th');
    }

    protected function MapData($datas, $fieldId, $fieldName)
    {
        $obj = [];
        foreach ($datas as $key => $value) {
            array_push($obj, ['id' => $value->{$fieldId}, 'name' => $value->{$fieldName}]);
        }
        return $obj;
    }


}

frontend/views/mh-concrete/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\widgets\DepDrop;
use yii\helpers\Url;
use common\models\MhProvince;
use yii\jui\DatePicker;


/* @var $this yii\web\View */
/* @var $model common\models\MhConcrete */
/* @var $form yii\widgets\ActiveForm */
//$id = yii::$app->user->identity->id;
$province = ArrayHelper::map(MhProvince::find()->asArray()->all(), 'province_id', 'province_name_th');
?>

<div class="mh-concrete-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data']
    ]); ?>

    <?='' //$form->field($model, 'con_desciption_product')->textInput(['maxlength' => true]) ?>

        

    <?='' //$form->field($model, 'con_strength')->textInput() ?>

    <?= $form->field($model, 'con_strength')->dropDownList([ 1 => '150', 2 => '180',
3 => '210', 4 => '240', 5 => '280', 6 => '300', 7 => '320', 8 => '350', 
9 => '380', 10 => '400', 11 => '420', ], ['prompt' => 'เลือก Strength (cube)'])->label('กำลังแรงอัด', ['style' => 'color:red']) ?>

    <?= $form->field($model, 'con_volume')->textInput()
    ->label('ปริมาณ', ['style' => 'color:red']) ?>   


    <?php $model->isNewRecord==1?
    $model->con_unit=1:$model->con_unit;?>
    <?= $form->field($model,'con_unit')->radioList([ 1 => 'cube', 2 => 'cylender', ])
    ->label('หน่วย', ['style' => 'color:red']) ?>   

    <?='' //$form->field($model, 'con_cube')->radio(['cube' => 'cube']) ?>

    <?='' //$form->field($model, 'con_cylender')->radio([0 => 'cylender']) ?>

    
    
    

    <?='' //$form->field($model, 'con_province_id')->textInput() ?>
   
    <?='' //$form->field($model, 'con_amphoe_id')->textInput() ?>
   
    <?='' //$form->field($model, 'con_district_id')->textInput() ?>

    <hr>

    <h4 style="color:red;">สถานที่จัดส่ง</h4>
    <h6 style="color:red;">*เลือกอย่างใดอย่างหนึ่ง</h6>

<div class="">  

    <div class="col-xs-12 col-sm-6 col-md-4">
        <?=
            $form
                ->field($model, 'con_province_id')
                
                ->dropdownList($province, [
                    'id' => 'ddl-province',
                    'prompt' => 'เลือกจังหวัด'
                ])
        ?>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <?=
            $form
                ->field($model, 'con_amphoe_id')
                ->widget(DepDrop::classname(), [
                    'options' => ['id' => 'ddl-amphoe'],
                    'data' => $amphoe,
                    'pluginOptions' => [
                        'depends' => ['ddl-province'],
                        'placeholder' => 'เลือกอำเภอ...',
                        'url' => Url::to(['/mh-concrete/get-amphoe'])
                    ]
                ]);
        ?>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <?=
            $form
                ->field($model, 'con_district_id')
                ->widget(DepDrop::classname(), [
                    'data' => $district,
                    'pluginOptions' => [
                        'depends' => ['ddl-province', 'ddl-amphoe'],
                        'placeholder' => 'เลือกตำบล...',
                        'url' => Url::to(['mh-concrete/get-district'])
                    ]
                ]);
        ?>
    </div>
    
    <?= $form->field($model, 'con_pic_map[]')->fileInput(['multiple' => true]) ?>
    <div class="well">
        <?= $model->getPhotosViewer(); ?>
    </div>


    <!--<?= $form->field($model, 'con_gps_transpot')->textInput(['maxlength' => true])
    ->input('con_gps_transpot', ['placeholder' => "เช่น 13.793933, 100.495085"])->label(false); ?>-->

</div>


<hr>



    <?='' //$form->field($model, 'con_pic_map')->textInput(['maxlength' => true]) ?>

    

    <?='' //$form->field($model, 'con_datetime')->textInput() ?>

    
    <div class="">
            <?= $form
                ->field($model, 'con_datetime')
                ->widget(DatePicker::classname(), [
                    'language' => 'th',
                    'dateFormat' => 'yyyy-MM-dd',
                    'clientOptions' => [
                        'changeMonth' => true,
                        'changeYear' => true,
                    ],
                    'options' => ['class' => 'form-control']
                ])
                ->label('วันที่ต้องการส่ง', ['style' => 'color:red'])
            ?>
    </div>



    <?= $form->field($model, 'con_duration')->radioList([ 1 => 'เช้า', 2 => 'บ่าย', ])
    ->label('ช่วงเวลาที่ต้องการส่ง', ['style' => 'color:red']) ?>

    <?= $form->field($model, 'con_name_contact')->textInput(['maxlength' => true])
    ->label('ชื่อติดต่อ', ['style' => 'color:red']) ?>

    <?= $form->field($model, 'con_tel_contact')->textInput()
    ->label('เบอร์โทรศัพท์', ['style' => 'color:red']) ?>

    <?= $form->field($model, 'con_other')->textInput(['maxlength' => true]) ?>

    <?='' //$form->field($model, 'updated_id')->textInput() ?>

    <?= $form->field($model, 'created_time')->textInput([
        'readonly' => true,
        'value' => (($model->created_time != null) && ($model->created_time != '0000-00-00 00:00:00')) ? $model->created_time : date('Y-m-d H:i:s')
    ]) ?>
    
    <?= $form->field($model, 'updated_time')->textInput([
        'readonly' => true,
        'value' => date('Y-m-d H:i:s')
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/mh-concrete/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\MhConcreteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mh-concrete-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'con_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'con_desciption_product') ?>

    <?= $form->field($model, 'con_strength') ?>

    <?= $form->field($model, 'con_volume') ?>

    <?php // echo $form->field($model, 'con_unit') ?>

    <?php // echo $form->field($model, 'con_cube') ?>

    <?php // echo $form->field($model, 'con_cylender') ?>

    <?php // echo $form->field($model, 'con_gps_transpot') ?>

    <?php // echo $form->field($model, 'con_province_id') ?>

    <?php // echo $form->field($model, 'con_amphoe_id') ?>

    <?php // echo $form->field($model, 'con_district_id') ?>

    <?php // echo $form->field($model, 'con_pic_map') ?>

    <?php // echo $form->field($model, 'con_datetime') ?>

    <?php // echo $form->field($model, 'con_duration') ?>

    <?php // echo $form->field($model, 'con_name_contact') ?>

    <?php // echo $form->field($model, 'con_tel_contact') ?>

    <?php // echo $form->field($model, 'con_other') ?>

    <?php // echo $form->field($model, 'updated_id') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'updated_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/mh-concrete/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConcrete */

$this->title = 'สั่งคอนกรีต';

//$this->params['breadcrumbs'][] = ['label' => 'คอนกรีตของฉัน', 'url' => ['mycon']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-concrete-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'amphoe' => [],
        'district' => [],
    ]) ?>

</div>

frontend/views/mh-concrete/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\MhConcreteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mh Concretes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-concrete-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Mh Concrete', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'con_id',
            'user_id',
            'con_desciption_product',
            'con_strength',
            'con_volume',
            //'con_unit',
            //'con_cube',
            //'con_cylender',
            //'con_gps_transpot',
            //'con_province_id',
            //'con_amphoe_id',
            //'con_district_id',
            //'con_pic_map',
            //'con_datetime',
            //'con_duration',
            //'con_name_contact',
            //'con_tel_contact',
            //'con_other',
            //'updated_id',
            //'created_time',
            //'updated_time',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

frontend/views/mh-concrete/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConcrete */
$userid = yii::$app->user->identity->id;
$this->title = 'แก้ไขข้อมูลคอนกรีต ' ;
if (Yii::$app->user->isGuest) {
        
    $this->params['breadcrumbs'][] = ['label' => 'รายการคอนกรีต', 'url' => ['index']];
    
} else {

    $this->params['breadcrumbs'][] = ['label' => 'ประวัติการสั่งคอนกรีตของฉัน', 'url' => ['mycon'], 'id' => $userid];

}
//$this->params['breadcrumbs'][] = ['label' => 'คอนกรีตของฉัน', 'url' => ['mycon']];
$this->params['breadcrumbs'][] = ['label' => $model->con_desciption_product, 'url' => ['view', 'id' => $model->con_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="mh-concrete-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'amphoe' => $amphoe,
        'district' => $district,
    ]) ?>

</div>