frontend/controllers/MhConcreteController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\MhConcrete;
use backend\models\MhConcreteSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use common\models\MhAmphoe;
use common\models\MhDistrict;

/**
 * MhConcreteController implements the CRUD actions for MhConcrete model.
 */
class MhConcreteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhConcrete models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $searchModel = new MhConcreteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view_all_conlist', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    

    public function actionMycon()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;

        $searchModel = new MhConcreteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider
        ->query
        ->where(['in', 'user_id', $user_id]);

        return $this->render('my_con', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            
        ]);
}

    /**
     * Displays a single MhConcrete model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $owner = false;

        $user_id = Yii::$app->user->id;
        if ($model->user_id == $user_id) {
            $owner = true;
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
            'owner' => $owner,
        ]);
    }

    /**
     * Creates a new MhConcrete model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        /*if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }*/
        $model = new MhConcrete();

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->con_pic_map = $model->uploadMultiple($model, 'con_pic_map');               
                
            }

            if(Yii::$app->request->isPost) {
                
                    $con_desciption_product = Yii::$app->request->post('MhConcrete[con_desciption_product]');
                    Yii::$app->mailer->compose()
                    ->setTo('fusefeaturing@gmail.com')
                    ->setFrom('fusefeaturing@gmail.com')
                    ->setSubject('ทดสอบ')
                    ->setHtmlBody('<b>'.$con_desciption_product.'</b>')
                    ->setBcc('fusefeaturing@gmail.com')
                    
                    ->send();
        
                  
                  
            }

            if ($model->save()) {
                //return $this->redirect(['view', 'id' => $model->job_id]);
                return $this->redirect(['view', 'id' => $model->con_id]);
            }

        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MhConcrete model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);


        $amphoe = ArrayHelper::map($this->getAmphoe($model->con_amphoe_id), 'id', 'name');
        $district = ArrayHelper::map($this->getDistrict($model->con_district_id), 'id', 'name');

        if ($model->load(Yii::$app->request->post())) {

            
            if ($model->validate()) {
                $model->con_pic_map = $model->uploadMultiple($model, 'con_pic_map');
            }

            if ($model->save()) {
                //return $this->redirect(['view', 'id' => $model->job_id]);
                return $this->redirect(['view', 'id' => $model->con_id]);
            }

        }

        return $this->render('update', [
            'model' => $model,
            'amphoe' => $amphoe,
            'district' => $district,
        ]);
    }

    /**
     * Deletes an existing MhConcrete model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhConcrete model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhConcrete the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhConcrete::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetAmphoe()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $province_id = $parents[0];
                $out = $this->getAmphoe($province_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionGetDistrict()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $province_id = empty($ids[0]) ? null : $ids[0];
            $amphoe_id = empty($ids[1]) ? null : $ids[1];
            if ($province_id != null) {
                $data = $this->getDistrict($amphoe_id);
                echo Json::encode(['output' => $data, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getAmphoe($id)
    {
        $datas = MhAmphoe::find()->where(['province_id' => $id])->all();
        return $this->MapData($datas, 'amphoe_id', 'amphoe_name_th');
    }

    protected function getDistrict($id)
    {
        $datas = MhDistrict::find()->where(['amphoe_id' => $id])->all();
        return $this->MapData($datas, 'district_id', 'district_name_th');
    }

    protected function MapData($datas, $fieldId, $fieldName)
    {
        $obj = [];
        foreach ($datas as $key => $value) {
            array_push($obj, ['id' => $value->{$fieldId}, 'name' => $value->{$fieldName}]);
        }
        return $obj;
    }


}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;


$currentUrl = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; //Url::canonical();
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <script>



btn.on('click', function(e) {
  e.preventDefault();
  $('html, body').animate({scrollTop:0}, '300');
});
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'headerContent' => Html::a('089-519-7777','tel:+66618728888',['class' => 'navbar-brand navbar-link']),
        
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        //Html::a('กลับไปที่ maxhome.co',"https://line.me/R/ti/p/%40maxhome"),
        //['label' => 'หน้าแรก', 'url' => ['https://maxhome.co/']],
        ['label' => 'หาช่างรับเหมาก่อสร้าง', 'url' => ['/mh-job/index']],
        ['label' => 'หาร้านวัสดุก่อสร้าง', 'url' => ['/mh-construction/index']],
        //['label' => 'ดูบทความ', 'url' => ['/site/contact']],
        
        //['label' => 'ดูสินค้า', 'url' => ['/mh-construction/index']],
        ['label' => 'หาสถาปนิก / วิศวกร', 'url' => ['/mh-architect-engineer/index']],
        ['label' => 'สั่งคอนกรีต', 'url' => ['/mh-concrete/create']],
        
    ];
    if (Yii::$app->user->isGuest) {
        
        $menuItems[] = ['label' => 'เข้าสู่ระบบ', 'url' => ['/site/login']];
    } else {
        $menuItems[] = ['label' => 'แก้ไขข้อมูลส่วนตัว', 'url' => ['/mh-user/profile']];
        
        
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'ออกจากระบบ (' . Yii::$app->user->identity->user_firstname . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container" style="padding-top: 110px;">
    
    <button onclick="topFunction()" id="myBtn" title="Go to top"><i class="fas fa-arrow-circle-up"></i></button>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>


<nav class="navbar-default navbar-fixed-bottom">
            <div class="container-fluid">

                <div class="row ">
                         
                <div id="wpfront-notification-bar" class="wpfront-fixed ">
    <table border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td>
                <div class="wpfront-message">ต้องการความช่วยเหลือติดต่อสอบถาม ทีมงาน MaxHome</div>
                    <div> 
                        <a class="wpfront-button" href="https://line.me/R/ti/p/%40maxhome"  target="_blank" >LINE ID : @MaxHome</a>
                    </div>
                </td>
            </tr>
        </table>
    </div>      
                    
                </div>
        </nav>


<!--<footer class="footer">
<div id="wpfront-notification-bar" class="wpfront-fixed ">
    <table border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td>
                <div class="wpfront-message"> โปรโมชั่น ส่วนลดพิเศษ ติดต่อทีมขาย</div>
                    <div> 
                        <a class="wpfront-button" href="https://line.me/R/ti/p/%40maxhome"  target="_blank" >LINE ID : @MaxHome</a>
                    </div>
                </td>
            </tr>
        </table>
    </div>



</footer>-->

<?php $this->endBody() ?>
<script>
//Get the button:
mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
</script>


</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
</html>
<?php $this->endPage() ?>